apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: dp-ns
type: Opaque
data:
  # Base64 encoded values
  # Example: echo -n 'your_value' | base64
  DB_PASSWORD: UDBzdGdyZXM=
  REDIS_PASSWORD: UmVkMXM=
  JWT_SECRET: SldUc2VjcmV0